# Basic configs
title: Website Name
email: email@mail.com


description: >- # this means to ignore newlines until "baseurl:"
    description


# URL configs
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


# Plugins
plugins:
  - jekyll-feed


# sass configs
sass:
    sass_dir: assets/styles
    style: compressed
#    sourcemap: never


# defaults frontmatter configs
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      title: "My default Title"


# includes
include: ['_pages']
